package fcatools.conexpng;

public enum ContextChangeEvents {
    CANCELCALCULATIONS, CONTEXTCHANGED, ATTRIBUTENAMECHANGED, NEWCONTEXT, LABELSCHANGED, STARTCALCULATION, ENDCALCULATION, TEMPORARYCONTEXTCHANGED, NEWLATTICE, LOADEDFILE;
}
